project:
  type: website
  output-dir: docs

website:
  title: "Woodpecker Niche Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - point_counts.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



